version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name       = "fit5225-team102-part4-notifications"
region           = "ap-southeast-2"
confirm_changeset = true
capabilities     = "CAPABILITY_IAM"
parameter_overrides = [
    "CognitoUserPoolId=ap-southeast-2_NgrJbyS3q",
    "CognitoClientId=5k2a9ipn97p3efqfev1gtl07r9",
    "MediaFilesStreamArn=arn:aws:dynamodb:ap-southeast-2:729985041330:table/fit5225-team102-media-files/stream/2026-05-28T13:17:36.059"
]
