AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: FIT5225 Team102 Part2 Model Service

Parameters:
  StageName:
    Type: String
    Default: prod

  UploadBucketName:
    Type: String
    Default: fit5225-team102-aussie-ecolens

  UploadPrefix:
    Type: String
    Default: uploads/

  ThumbnailPrefix:
    Type: String
    Default: thumbnails/

  Part3UpsertUrl:
    Type: String
    Default: https://5jo3ferouh.execute-api.ap-southeast-2.amazonaws.com/prod/data/media

  Part3AuthToken:
    Type: String
    Default: ""

  ModelBucket:
    Type: String
    Default: fit5225-team102-aussie-ecolens

  MdModelKey:
    Type: String
    Default: models/mdv5a.pt

  SpeciesModelKey:
    Type: String
    Default: models/model.pt

  LabelsKey:
    Type: String
    Default: models/labels.txt

  EnableModelInference:
    Type: String
    Default: "true"

Resources:
  AutoTagFromS3Function:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: part2-autotag
      DockerContext: .
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      Timeout: 300
      MemorySize: 3008
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref UploadBucketName
          UPLOAD_PREFIX: !Ref UploadPrefix
          THUMBNAIL_PREFIX: !Ref ThumbnailPrefix
          TEMP_PREFIX: temp/
          PART3_UPSERT_URL: !Ref Part3UpsertUrl
          PART3_AUTH_TOKEN: !Ref Part3AuthToken
          MODEL_BUCKET: !Ref ModelBucket
          MD_MODEL_KEY: !Ref MdModelKey
          SPECIES_MODEL_KEY: !Ref SpeciesModelKey
          LABELS_KEY: !Ref LabelsKey
          MIN_DETECTION_CONF: "0.2"
          ENABLE_MODEL_INFERENCE: !Ref EnableModelInference
          MODEL_NAME: wildlife-detector
          MODEL_VERSION: v1
          FFMPEG_PATH: /opt/bin/ffmpeg
          VIDEO_FPS: "1"
          VIDEO_MAX_FRAMES: "5"
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UploadBucketName
        - S3ReadPolicy:
            BucketName: !Ref ModelBucket
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

Outputs:
  FunctionName:
    Description: Part B auto-tag Lambda function name
    Value: !Ref AutoTagFromS3Function
